apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml

resources:
- ../../base
- ingress.yml
- pdb.yml

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - DATABASE_HOST=<% index .Params `productionDatabaseHostname` %>
    - DATABASE_NAME=<% .Name %>_production
    - ENVIRONMENT=production
