name: Pull request
on:
  pull_request:
    branches: ['*']
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      build_env: production
    steps:
    - uses: actions/checkout@v2
    - name: Run Unit Tests
      uses: actions/setup-go@v2
    - run: go test -v ./...
