apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- deployment.yml

resources:
- ingress.yaml
- pdb.yaml

configMapGenerator:
- name: <% .Name %>-config
  behavior: merge
  literals:
    - DATABASE_HOST=<% index .Params `productionDatabaseHostname` %>
    - DATABASE_NAME=<% .Name %>_production
    - ENVIRONMENT=production
