apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: backend-service
build:
  tagPolicy:
    sha256: {}
  artifacts:
      - image: <% index .Params `accountId` %>.dkr.ecr.<% index .Params `region` %>.amazonaws.com/<% .Name %>
deploy:
  kustomize:
    paths:
    - kubernetes.tmp/base
profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - kubernetes.tmp/overlays/staging
